### ISSUE TITLE
Crash when specifying excluded dependencies

### ISSUE THREAD

**Issue by sanmai-NL** [fredrikaverpil/creosote#172]
### What happened?

Creosote crashed. 

### Reproduction steps

```console
$ creosote --exclude-deps python-multipart uvicorn --verbose

Creosote version: 2.6.1
Command: creosote --exclude-deps python-multipart uvicorn --verbose
Arguments: Namespace(verbose=True, format='default', paths=['src'], sections=['project.dependencies'], exclude_deps=['python-multipart', 'uvicorn'], deps_file='pyproject.toml', venvs=['.venv'], features=[])
Imports found in code:
Parsing pyproject.toml for dependencies...
['project.dependencies']: []
Detected PEP-621 toml section in pyproject.toml
No dependencies found in section project.dependencies
Found dependencies in pyproject.toml: 
Traceback (most recent call last):
  File "/Users/USER/product/.venv/bin/creosote", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/USER/.venv/lib/python3.11/site-packages/creosote/cli.py", line 194, in main
    excluded_deps_and_not_installed = parsers.get_excluded_deps_which_are_not_installed(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/.venv/lib/python3.11/site-packages/creosote/parsers.py", line 228, in get_excluded_deps_which_are_not_installed
    if excluded_dep_name not in get_installed_dependency_names(venv):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/.venv/lib/python3.11/site-packages/creosote/parsers.py", line 212, in get_installed_dependency_names
    site_packages = Path(venv).glob("**/site-packages").__next__()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

### Relevant log output

See previous section.

It does mention a `.venv` directory that doesn't exist yet in the current directory, but it uses the one from the parent directory.

**Comment by sanmai-NL** [comment]
@lesleslie 
I understand the venv missing is a fault, but the the way this is handled in the UI is rough and not clear to the user.

The second item I know about, I was personally involved in the implementation of Creosote's PDM support.

**Comment by fredrikaverpil** [comment]
Please update to creosote 2.6.2 and let me know if you still see this crash. This is what I see when there's no `.venv` folder with creosote 2.6.2:

![image](https://github.com/fredrikaverpil/creosote/assets/994357/31455c54-c01b-45cf-9837-61a322ad6aa7)

**Comment by sanmai-NL** [comment]
I don't see the crash anymore.
