### ISSUE TITLE
creosote fails on non-UTF8 files

### ISSUE THREAD

**Issue by bramp** [fredrikaverpil/creosote#208]
### What happened?

I expect creosote to support all files, but it fails on non-UTF8 files. Specifically one using `coding: cp1252`.

### Reproduction steps

1. Run `pip install xlrd==0.7.1`
1. Run `creosote --verbose -p .`

### Relevant log output

```shell
❯ creosote --verbose -p .
Creosote version: 3.0.1
Command: creosote --verbose -p .
Default configuration (may have loaded pyproject.toml): Config(format='default', paths=['src'], sections=['project.dependencies'], exclude_deps=[], deps_file='pyproject.toml', venvs=['/Users/bramp/personal/which_filament/importer/.venv'], features=[])
Arguments: Namespace(verbose=True, format='default', paths=['.'], sections=['project.dependencies'], exclude_deps=[], deps_file='pyproject.toml', venvs=['/Users/bramp/personal/which_filament/importer/.venv'], features=[])
Parsing fetch.py
... (snip) ...
Parsing .venv/bin/pdf2txt.py
Parsing .venv/bin/dumppdf.py
Parsing .venv/bin/runxlrd.py
Traceback (most recent call last):
  File "/Users/bramp/personal/which_filament/importer/.venv/bin/creosote", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/bramp/personal/which_filament/importer/.venv/lib/python3.12/site-packages/creosote/cli.py", line 25, in main
    imports = parsers.get_module_names_from_code(args.paths)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bramp/personal/which_filament/importer/.venv/lib/python3.12/site-packages/creosote/parsers.py", line 220, in get_module_names_from_code
    for import_info in get_module_info_from_python_file(path=str(resolved_path)):
  File "/Users/bramp/personal/which_filament/importer/.venv/lib/python3.12/site-packages/creosote/parsers.py", line 189, in get_module_info_from_python_file
    root = ast.parse(fh.read(), path)
                     ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 41: invalid start byte

```

The file in question is here: https://github.com/python-excel/xlrd/blob/0.7.1/scripts/runxlrd.py and it's getting hung up on the © copyright symbol.

**Comment by fredrikaverpil** [comment]
Hey @bramp 👋  and thanks for the report!

I see two possible solutions:

### Ignore errors

We can tell Python to ignore or replace invalid characters when reading the file. This might result in loss of data, but it will allow Creosote to continue running, and likely not choke on imports, which is what's important during this AST parsing:

```python
with open(path, encoding="utf-8", errors="ignore") as fh:
    root = ast.parse(fh.read(), path)
```

### Replace errors

And as an alternative, we could replace invalid characters with the Unicode replacement character (U+FFFD):

```python
with open(path, encoding="utf-8", errors="replace") as fh:
    root = ast.parse(fh.read(), path)
```

### PR #209

I whipped up a PR where I went for the second option. It would be helpful if you could try this out for me on your files. You can install creosote from git, like this for example:

```bash
# Creosote build from PR https://github.com/fredrikaverpil/creosote/issues/209
$ pipx install --suffix=@209 --force git+https://github.com/fredrikaverpil/creosote.git@refs/pull/209/head
$ creosote@209 --venv .venv ...
$ pipx uninstall creosote@209
```

**Comment by fredrikaverpil** [comment]
Maybe I spoke too soon, seems like there are other issues here. This seems to be Python 2.x which is not supported by Creosote:

```
❯ pip install xlrd==0.7.1
Collecting xlrd==0.7.1
  Downloading xlrd-0.7.1.zip (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.4/125.4 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: xlrd
  Building wheel for xlrd (setup.py) ... done
  Created wheel for xlrd: filename=xlrd-0.7.1-py3-none-any.whl size=117959 sha256=c4f80c8d5abf30b826eb7354d6569e6b91ad3870560df9739fa2c77fe0eba20e
  Stored in directory: /Users/fredrik/Library/Caches/pip/wheels/82/5b/79/a6610cd31788f61b35af4028b07f825a705b048ce47d0746ad
Successfully built xlrd
Installing collected packages: xlrd
Successfully installed xlrd-0.7.1


❯ creosote --verbose -p .
Creosote version: 3.0.1
Command: creosote --verbose -p .
Default configuration (may have loaded pyproject.toml): Config(format='default', paths=['src'], sections=['project.dependencies'], exclude_deps=[], deps_file='pyproject.toml', venvs=['/Users/fredrik/code/public/creosote/.venv'], features=[])
Arguments: Namespace(deps_file='pyproject.toml', exclude_deps=[], features=[], format='default', paths=['.'], sections=['project.dependencies'], venvs=['/Users/fredrik/code/public/creosote/.venv'], verbose=True)
Parsing tests/test_config_loading.py
Parsing tests/conftest.py
Parsing tests/test_dependency_reader.py
Parsing tests/__init__.py
Parsing tests/test_integration.py
Parsing tests/test_custom_append_action.py
Parsing tests/fixtures/integration.py
Parsing .venv/bin/activate_this.py
Parsing .venv/bin/runxlrd.py
Traceback (most recent call last):
  File "/Users/fredrik/code/public/creosote/.venv/bin/creosote", line 8, in <module>
    sys.exit(main())
  File "/Users/fredrik/code/public/creosote/src/creosote/cli.py", line 25, in main
    imports = parsers.get_module_names_from_code(args.paths)
  File "/Users/fredrik/code/public/creosote/src/creosote/parsers.py", line 220, in get_module_names_from_code
    for import_info in get_module_info_from_python_file(path=str(resolved_path)):
  File "/Users/fredrik/code/public/creosote/src/creosote/parsers.py", line 189, in get_module_info_from_python_file
    root = ast.parse(fh.read(), path)
  File "/Users/fredrik/.pkgx/python.org/v3.8.18/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File ".venv/bin/runxlrd.py", line 54
    print "cell %s%d: type=%d, data: %r, xfx: %s" \
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("cell %s%d: type=%d, data: %r, xfx: %s" \)?
```

**Comment by fredrikaverpil** [comment]
I pushed a quick fix for that second problem too. Let me know how this works for you. 😄

**Comment by bramp** [comment]
I agree, replace seems reasonable.

I don't use `pipx` (but I just learnt what that is, and might in future), instead I did:

```
pip uninstall creosote
pip install git+https://github.com/fredrikaverpil/creosote.git@fix-unicodedecodeerror
```

and re-ran my test, and it indeed works.
